version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

setup: true

jobs:
  build_and_test:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      # - node/install-packages:
      #     pkg-manager: yarn
      # - run:
      #     command: yarn test
      #     name: Run tests
      # - run:
      #     command: yarn build
      #     name: Build app
      # - persist_to_workspace:
      #     root: ~/project
      #     paths:
      #       - .
  deploy:
     docker:
       - image: cimg/node:17.2.0   
     steps:
       - checkout
       - run:
           name: Deploy Main to Heroku
           command: |
             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
    
workflows:
  on_commit:
    jobs:
      - build_and_test
      # Follow instruction here to authenticate git for Heroku: https://devcenter.heroku.com/articles/git#http-git-authentication
      # The following code may be uncommented, onnce HEROKU_API_KEY & HEROKU_APP_NAME environemnt variables are present
      # Read more: https://circleci.com/docs/2.0/env-vars/
      # - deploy:
      #     requires:
      #       - build_and_test # only deploy if the build_and_test job has completed
      #     filters:
      #       branches:
      #         only: master # only deploy when on main/master
      - deploy:
          requires:
            - build_and_test # only run deploy-via-git job if the build job has completed
          filters:
            branches:
              only: main # only run deploy-via-git job on main branch